### ISSUE TITLE
How to run the trustGraph?

### ISSUE THREAD

**Issue by ShakibaZar** [AdamColton/trustGraph#1]
Hi AdamColton, could you give me some instructions how to use your code? I didn't find any main method to run the sample class. Looking forward to your reply. Thank you for your time.

**Comment by AdamColton** [comment]
Just a heads up, this code is old and not really complete. There's no main because it's intended to imported. You can see it works by running the tests. This may also help: https://godoc.org/github.com/AdamColton/trustGraph

All I've really done here is compute the eigenvector, the really insight of the paper is how to distribute that calculation which I never really did.

**Comment by ShakibaZar** [comment]
Thanks for your reply.
